#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.

class Integer
	def tri() self * (self + 1) / 2 end
	def pen() self * (3 * self - 1) / 2 end
	def hex() self * (2 * self - 1) end
end

ltri = []; lpen = []; lhex = []
(1..1E5).map{|i| ltri << i.tri; lpen << i.pen; lhex << i.hex}
puts ((ltri & lpen) & lhex).inspect